spring:
  datasource:
    url: jdbc:mariadb://19341.synology.me:3306/homepage
    username: jwlee
    password: Epsltm1124!
    hikari:
      connection-test-query: SELECT 1   # 연결이 정상적으로 되었는지 확인하는 Test Query
      idle-timeout: 60000               # 연결된 DB 커넥션 중 사용하지 않은게 있으면 해당 설정된 시간 이후 자동 해제됨
      connection-timeout: 30000         # 커넥션을 얻기위한 대기시간

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.orm.jdbc.bind: trace
